### ISSUE TITLE
STUDY / EasyBpy

### ISSUE THREAD

**Issue by enzyme69** [enzyme69/blendersushi#896]
LIST EASYBPY:

`['Euler', 'Matrix', 'Vector', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'active_object', 'add_armature', 'add_array', 'add_bevel', 'add_boolean', 'add_build', 'add_cast', 'add_cloth', 'add_cloth_physics', 'add_collision', 'add_collision_physics', 'add_corrective_smooth', 'add_curve', 'add_data_transfer', 'add_decimate', 'add_displace', 'add_dynamic_paint', 'add_dynamic_paint_physics', 'add_edge_split', 'add_explode', 'add_fluid', 'add_fluid_physics', 'add_force_field_physics', 'add_hook', 'add_laplacian_deform', 'add_laplacian_smooth', 'add_lattice', 'add_mask', 'add_material_to_object', 'add_mesh_cache', 'add_mesh_deform', 'add_mesh_sequence_cache', 'add_mirror', 'add_modifier', 'add_multires', 'add_normal_edit', 'add_ocean', 'add_particle_instance', 'add_particle_system', 'add_remesh', 'add_rigid_body_constraint_physics', 'add_rigid_body_physics', 'add_screw', 'add_shrinkwrap', 'add_simple_deform', 'add_simulation', 'add_skin', 'add_smooth', 'add_soft_body', 'add_soft_body_physics', 'add_solidify', 'add_subsurf', 'add_surface', 'add_surface_deform', 'add_triangulate', 'add_uv_project', 'add_uv_warp', 'add_vertex_weight_edit', 'add_vertex_weight_mix', 'add_vertex_weight_proximity', 'add_warp', 'add_wave', 'add_weighted_normal', 'add_weld', 'add_wireframe', 'ao', 'apply_all_transforms', 'apply_location', 'apply_rotation', 'apply_rotation_and_scale', 'apply_scale', 'bpy', 'clear_unused_data', 'clear_unwanted_data', 'collection_exists', 'copy_object', 'create_circle', 'create_collection', 'create_cone', 'create_cube', 'create_cylinder', 'create_grid', 'create_ico_sphere', 'create_material', 'create_mesh', 'create_monkey', 'create_node', 'create_node_link', 'create_object', 'create_plane', 'create_suzanne', 'create_text_object', 'create_texture', 'create_torus', 'create_uv_sphere', 'current_frame', 'cursor_to_active', 'cursor_to_grid', 'cursor_to_selection', 'cursor_to_world_origin', 'delete_collection', 'delete_hierarchy', 'delete_material', 'delete_object', 'delete_objects', 'delete_objects_in_collection', 'delete_selected_objects', 'delete_text_object', 'delete_texture', 'deselect_all_objects', 'deselect_object', 'display_as_bounds', 'display_as_solid', 'display_as_textured', 'display_as_wire', 'duplicate_collection', 'duplicate_object', 'edit_mode', 'frame_end', 'frame_start', 'geometry_to_origin', 'get_active_collection', 'get_active_object', 'get_all_collections', 'get_all_objects', 'get_all_textures', 'get_col', 'get_collection', 'get_cursor_location', 'get_cursor_rotation', 'get_cursor_rotation_mode', 'get_edges', 'get_faces', 'get_lines_in_text_object', 'get_list_of_collections', 'get_list_of_objects', 'get_list_of_textures', 'get_material', 'get_material_names_from_object', 'get_materials', 'get_materials_from_object', 'get_mesh_from_object', 'get_mode', 'get_modifier', 'get_node_links', 'get_node_tree', 'get_obj', 'get_object', 'get_object_collection', 'get_object_collections', 'get_objects_from_collection', 'get_polygons', 'get_render_pixel_aspect_ratio', 'get_render_resolution', 'get_render_resolution_percentage', 'get_scene', 'get_selected_object', 'get_selected_objects', 'get_texture', 'get_vertices', 'hide', 'hide_in_render', 'hide_in_viewport', 'hide_object', 'instance_object', 'invert_selection', 'is_string', 'link_object_to_collection', 'link_objects_to_collection', 'location', 'make_vector', 'material_exists', 'math', 'move_object_to_collection', 'move_objects_to_collection', 'object_exists', 'object_mode', 'origin_to_centermass_surface', 'origin_to_centermass_volume', 'origin_to_cursor', 'origin_to_geometry', 'radians', 'remove_material', 'remove_material_from_object', 'remove_modifier', 'rename_object', 'rename_texture', 'render_animation', 'render_aspect_ratio', 'render_image', 'render_resolution', 'render_resolution_percentage', 'revese_rotation_on_euler', 'rotate_around_axis', 'rotate_around_global_x', 'rotate_around_global_y', 'rotate_around_global_z', 'rotate_around_local_x', 'rotate_around_local_y', 'rotate_around_local_z', 'rotate_around_x', 'rotate_around_y', 'rotate_around_z', 'rotate_vector', 'rotation', 'scale', 'scale_along_axis', 'scale_along_global_axis', 'scale_along_global_x', 'scale_along_global_y', 'scale_along_global_z', 'scale_along_local_x', 'scale_along_local_y', 'scale_along_local_z', 'scale_along_x', 'scale_along_y', 'scale_along_z', 'scale_perpendicular_to_x', 'scale_perpendicular_to_y', 'scale_perpendicular_to_z', 'scale_uniform', 'scale_vector', 'sculpt_mode', 'select_all_armatures', 'select_all_cameras', 'select_all_curves', 'select_all_empties', 'select_all_greace_pencils', 'select_all_hair', 'select_all_lattices', 'select_all_light_probes', 'select_all_meshes', 'select_all_metas', 'select_all_objects', 'select_all_point_clouds', 'select_all_speakers', 'select_all_surfaces', 'select_all_text', 'select_all_volumes', 'select_object', 'selected_object', 'selection_to_active', 'selection_to_cursor_with_offset', 'selection_to_cursor_without_offset', 'selection_to_grid', 'set_active_collection', 'set_current_frame', 'set_cursor_location', 'set_edit_mode', 'set_end_frame', 'set_frame', 'set_frame_end', 'set_frame_interval', 'set_frame_start', 'set_frame_step', 'set_geometry_to_origin', 'set_material_use_nodes', 'set_mode', 'set_object_mode', 'set_origin_to_centermass_surface', 'set_origin_to_centermass_volume', 'set_origin_to_cursor', 'set_origin_to_geometry', 'set_pivot_point_to_active_element', 'set_pivot_point_to_bounding_box_center', 'set_pivot_point_to_cursor', 'set_pivot_point_to_individual_origins', 'set_pivot_point_to_median', 'set_render_engine_cycles', 'set_render_engine_eevee', 'set_render_engine_to_cycles', 'set_render_engine_to_eevee', 'set_render_fps', 'set_render_percent', 'set_render_percentage', 'set_render_pixel_aspect_ratio', 'set_render_resolution', 'set_render_resolution_percentage', 'set_sculpt_mode', 'set_smooth_angle', 'set_start_frame', 'set_texture_paint_mode', 'set_vertex_paint_mode', 'set_weight_paint_mode', 'shade_flat', 'shade_object_flat', 'shade_object_smooth', 'shade_smooth', 'show', 'show_in_render', 'show_in_viewport', 'show_object', 'so', 'texture_paint_mode', 'translate_along_axis', 'translate_along_global_x', 'translate_along_global_y', 'translate_along_global_z', 'translate_along_local_x', 'translate_along_local_y', 'translate_along_local_z', 'translate_along_x', 'translate_along_y', 'translate_along_z', 'translate_vector', 'unhide', 'unhide_in_render', 'unhide_in_viewport', 'unhide_object', 'unlink_object_from_collection', 'unlink_objects_from_collection', 'vertex_paint_mode', 'weight_paint_mode']`

**Comment by enzyme69** [comment]
>>> from easybpy import *
>>> create_suzanne(
create_suzanne()
>>> create_suzanne()
bpy.data.objects['Suzanne']

>>> create_ico_sphere(
create_ico_sphere()
>>> create_ico_sphere()
bpy.data.objects['Icosphere']

>>> translate_
              along_axis(
              along_global_x(
              along_global_y(
              along_global_z(
              along_local_x(
              along_local_y(
              along_local_z(
              along_x(
              along_y(
              along_z(
              vector(
>>> translate_along_
                    axis(
                    global_x(
                    global_y(
                    global_z(
                    local_x(
                    local_y(
                    local_z(
                    x(
                    y(
                    z(
>>> translate_along_x(5)
>>> translate_along_x(-2)
>>> create_torus(
create_torus()
>>> create_torus()
bpy.data.objects['Torus']

**Comment by enzyme69** [comment]
>>> create_material('Red')
bpy.data.materials['Red']

>>> create_material('Green')
bpy.data.materials['Green']

>>> create_material('Blue')
bpy.data.materials['Blue']

>>> add_m
         ask(
         aterial_to_object(
         esh_cache(
         esh_deform(
         esh_sequence_cache(
         irror(
         odifier(
         ultires(
>>> add_ma
          sk(
          terial_to_object(
>>> add_material_to_object(
add_material_to_object(ref, matname)
>>> add_material_to_object('Torus', 'Red')
>>> add_material_to_object('Suzanne', 'Green')
>>> add_material_to_object('Icosphere', 'Blule')
>>> add_material_to_object('Icosphere', 'Blue')
>>> get_material
                (
                _names_from_object(
                s(
                s_from_object(
>>> get_material('Red).Diffuse_Color = (1,0,0,1)
  File "<blender_console>", line 1
    get_material('Red).Diffuse_Color = (1,0,0,1)
                                               ^
SyntaxError: EOL while scanning string literal

>>> get_material('Red)
  File "<blender_console>", line 1
    get_material('Red)
                     ^
SyntaxError: EOL while scanning string literal

>>> get_material('Red').Diffuse_Color = (1,0,0,1)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: 'Material' object has no attribute 'Diffuse_Color'

>>> get_material('Red').DiffuseColor = (1,0,0,1)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: 'Material' object has no attribute 'DiffuseColor'

>>> get_material('Red').diffuse_collor = (1,0,0,1)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
AttributeError: 'Material' object has no attribute 'diffuse_collor'

>>> get_material('Red').diffuse_color = (1,0,0,1)
>>> get_material('Green').diffuse_color = (0,1,0,1)
>>> get_material('Blue').diffuse_color = (0,0,1,1)
>>>
